services:
  db:
    image: mysql:latest
    container_name: ${PROJECT_NAME}-db
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - /home/${USER}/${PROJECT_NAME}:/var/lib/mysql
  app:
    image: amazoncorretto:22-alpine3.19
    container_name: ${PROJECT_NAME}-app
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${APP_PORT}:8080"
