spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:galvanica}
    driver-class-name: com.mysql.cj.jdbc.Driver
